extern VG_REGPARM(1) UWord MC_(helperc_LOADV32be_asm) ( Addr a );
extern VG_REGPARM(1) UWord MC_(helperc_LOADV32le_asm) ( Addr a );

asm(
".text							\n"
".type vgMemCheck_helperc_LOADV32be_asm, @function	\n"
".globl vgMemCheck_helperc_LOADV32be_asm		\n"
"vgMemCheck_helperc_LOADV32be_asm:			\n"
"	push   %ebx					\n"
"	mov    %eax,%ebx				\n"
"	sub    $0x8,%esp				\n"
"	test   $0x3,%al					\n"
"	jne    Lbe2					\n"
"	shr    $0x10,%eax				\n"
"	mov    0xc060(,%eax,4),%edx			\n"
"	movzwl %bx,%eax					\n"
"	shr    $0x2,%eax				\n"
"	movzbl (%edx,%eax,1),%edx			\n"
"	cmp    $0xaa,%edx				\n"
"	jne    Lbe3 					\n"
"	xor    %eax,%eax				\n"
"Lbe1:	add    $0x8,%esp				\n"
"	pop    %ebx					\n"
"	ret    						\n"
"Lbe3:	or     $0xffffffff,%eax				\n"
"	cmp    $0x55,%edx				\n"
"	je     Lbe1					\n"
"Lbe2:	mov    $0x1,%ecx				\n"
"	mov    %ebx,%eax				\n"
"	mov    $0x20,%edx				\n"
"	call   vgMemCheck_helperc_STOREV16be		\n"
"	jmp    Lbe1					\n"
);

asm(
".text							\n"
".type vgMemCheck_helperc_LOADV32le_asm, @function	\n"
".globl vgMemCheck_helperc_LOADV32le_asm		\n"
"vgMemCheck_helperc_LOADV32le_asm:			\n"
"	push   %ebx					\n"
"	mov    %eax,%ebx				\n"
"	sub    $0x8,%esp				\n"
"	test   $0x3,%al					\n"
"	jne    Lle2					\n"
"	shr    $0x10,%eax				\n"
"	mov    0xc060(,%eax,4),%edx			\n"
"	movzwl %bx,%eax					\n"
"	shr    $0x2,%eax				\n"
"	movzbl (%edx,%eax,1),%edx			\n"
"	cmp    $0xaa,%edx				\n"
"	jne    Lle3					\n"
"	xor    %eax,%eax				\n"
"Lle1:	add    $0x8,%esp				\n"
"	pop    %ebx					\n"
"	ret						\n"
"Lle3:	or     $0xffffffff,%eax				\n"
"	cmp    $0x55,%edx				\n"
"	je     Lle1					\n"
"Lle2:	xor    %ecx,%ecx				\n"
"	mov    %ebx,%eax				\n"
"	mov    $0x20,%edx				\n"
"	call   vgMemCheck_helperc_STOREV16le		\n"
"	jmp    Lle1					\n"
);
